version: '3'
services:
  php:
    build: ./docker/php
    ports:
      - "9000"
    volumes:
      - ./source:/var/www/html
    hostname: php-host
    links:
      - mysql
      - mongo
      - elasticsearch
      - rabbitmq

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./source:/var/www/html
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    hostname: nginx-host

  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5671:5671"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=eiGhao8o

  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=root
      - MYSQL_PASSWORD=WaNoam4h
      - MYSQL_ROOT_PASSWORD=WaNoam4h
    hostname: mysql-host

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./source:/var/www/html
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aoCh5lei

  elasticsearch:
    image: elasticsearch:6.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch:/data

volumes:
  db_data:
  elasticsearch:
